"""Constants for the auth package."""

ROLE_ADMIN = "admin"  # legacy alias → org_admin permissions
ROLE_MEMBER = "member"  # legacy alias → user permissions

ROLE_SUPER_ADMIN = "super_admin"
ROLE_ORG_ADMIN = "org_admin"
ROLE_ORG_MANAGER = "org_manager"
ROLE_USER = "user"

NON_OVERRIDABLE_PERMISSIONS = {"create_super_admin", "create_org_admin", "access_admin_panel"}

PERMISSION_DEFINITIONS: dict[str, dict[str, str]] = {
    "view_org": {"label": "View Organization", "description": "Can list and retrieve organizations.", "resource": "org"},
    "create_org": {"label": "Create Organization", "description": "Can create new organizations.", "resource": "org"},
    "edit_org": {"label": "Edit Organization", "description": "Can update organizations.", "resource": "org"},
    "delete_org": {"label": "Delete Organization", "description": "Can soft-delete organizations.", "resource": "org"},
    "view_user": {"label": "View User", "description": "Can list and retrieve users.", "resource": "user"},
    "create_user": {"label": "Create User", "description": "Can provision new users.", "resource": "user"},
    "edit_user": {"label": "Edit User", "description": "Can update users.", "resource": "user"},
    "delete_user": {"label": "Delete User", "description": "Can soft-delete users.", "resource": "user"},
    "view_agent": {"label": "View Agent", "description": "Can list and retrieve agents.", "resource": "agent"},
    "create_agent": {"label": "Create Agent", "description": "Can create new agents.", "resource": "agent"},
    "edit_agent": {"label": "Edit Agent", "description": "Can update agents.", "resource": "agent"},
    "delete_agent": {"label": "Delete Agent", "description": "Can soft-delete agents.", "resource": "agent"},
    "view_tool": {"label": "View Tool", "description": "Can list and retrieve tools.", "resource": "tool"},
    "create_tool": {"label": "Create Tool", "description": "Can create new tools.", "resource": "tool"},
    "edit_tool": {"label": "Edit Tool", "description": "Can update tools.", "resource": "tool"},
    "delete_tool": {"label": "Delete Tool", "description": "Can soft-delete tools.", "resource": "tool"},
    "view_db_connection": {"label": "View DB Connection", "description": "Can list and retrieve DB connections.", "resource": "db_connection"},
    "create_db_connection": {"label": "Create DB Connection", "description": "Can create new DB connections.", "resource": "db_connection"},
    "edit_db_connection": {"label": "Edit DB Connection", "description": "Can update DB connections.", "resource": "db_connection"},
    "delete_db_connection": {"label": "Delete DB Connection", "description": "Can soft-delete DB connections.", "resource": "db_connection"},
    "view_chat": {"label": "View Chat", "description": "Can list and retrieve chat messages.", "resource": "chat"},
    "create_chat": {"label": "Create Chat", "description": "Can send messages in a chat session.", "resource": "chat"},
    "edit_chat": {"label": "Edit Chat", "description": "Can update chat messages.", "resource": "chat"},
    "delete_chat": {"label": "Delete Chat", "description": "Can delete chat messages.", "resource": "chat"},
    "view_chat_session": {"label": "View Chat Session", "description": "Can list and retrieve chat sessions.", "resource": "chat_session"},
    "create_chat_session": {"label": "Create Chat Session", "description": "Can start new chat sessions.", "resource": "chat_session"},
    "edit_chat_session": {"label": "Edit Chat Session", "description": "Can rename and update chat sessions.", "resource": "chat_session"},
    "delete_chat_session": {"label": "Delete Chat Session", "description": "Can delete chat sessions.", "resource": "chat_session"},
    "view_trace": {"label": "View Trace", "description": "Can view tracing and observability data.", "resource": "tracing"},
    "view_tool_registry": {"label": "View Tool Registry", "description": "Can list and retrieve tool registry entries.", "resource": "tool_registry"},
    "create_super_admin": {"label": "Create Super Admin", "description": "Can provision users with the super_admin role.", "resource": "user"},
    "create_org_admin": {"label": "Create Org Admin", "description": "Can provision users with the org_admin role.", "resource": "user"},
    "access_admin_panel": {"label": "Access Admin Panel", "description": "Can sign in to the /admin panel.", "resource": "user"},
    "view_widget": {"label": "View Widget", "description": "Can list and retrieve embeddable chatbot widgets.", "resource": "widget"},
    "create_widget": {"label": "Create Widget", "description": "Can create new embeddable chatbot widgets.", "resource": "widget"},
    "edit_widget": {"label": "Edit Widget", "description": "Can update embeddable chatbot widgets, including regenerating their API key.", "resource": "widget"},
    "delete_widget": {"label": "Delete Widget", "description": "Can soft-delete embeddable chatbot widgets.", "resource": "widget"},
    "view_team": {"label": "View Team", "description": "Can list and retrieve teams.", "resource": "team"},
    "create_team": {"label": "Create Team", "description": "Can create new teams.", "resource": "team"},
    "edit_team": {"label": "Edit Team", "description": "Can update teams and manage their members.", "resource": "team"},
    "delete_team": {"label": "Delete Team", "description": "Can soft-delete teams.", "resource": "team"},
    "view_role_permissions": {"label": "View Role Permissions", "description": "Can view the permission catalog and a role's granted permissions.", "resource": "role_permission"},
    "edit_role_permissions": {"label": "Edit Role Permissions", "description": "Can customize org_manager/user role permissions for their own organization.", "resource": "role_permission"},
    "view_schedule": {"label": "View Schedule", "description": "Can list and retrieve scheduled agent runs.", "resource": "schedule"},
    "create_schedule": {"label": "Create Schedule", "description": "Can schedule an agent to run automatically.", "resource": "schedule"},
    "edit_schedule": {"label": "Edit Schedule", "description": "Can update, pause, and resume schedules.", "resource": "schedule"},
    "delete_schedule": {"label": "Delete Schedule", "description": "Can soft-delete schedules.", "resource": "schedule"},
    "view_project": {"label": "View Project", "description": "Can list and retrieve projects.", "resource": "project"},
    "create_project": {"label": "Create Project", "description": "Can create new projects.", "resource": "project"},
    "edit_project": {"label": "Edit Project", "description": "Can update projects and manage their files/skills.", "resource": "project"},
    "delete_project": {"label": "Delete Project", "description": "Can soft-delete projects.", "resource": "project"},
    "view_knowledge_base": {"label": "View Knowledge Base", "description": "Can list and retrieve knowledge bases and their documents.", "resource": "knowledge_base"},
    "create_knowledge_base": {"label": "Create Knowledge Base", "description": "Can create knowledge bases and upload documents.", "resource": "knowledge_base"},
    "edit_knowledge_base": {"label": "Edit Knowledge Base", "description": "Can update knowledge bases and reassign documents.", "resource": "knowledge_base"},
    "delete_knowledge_base": {"label": "Delete Knowledge Base", "description": "Can soft-delete knowledge bases and their documents.", "resource": "knowledge_base"},
}

ROLE_DEFINITIONS = {
    ROLE_SUPER_ADMIN: {
        "label": "Super Admin",
        "description": "Full access across all organizations.",
        "assign_permission": "create_super_admin",
        "permissions": {
            "view_org": True, "create_org": True, "edit_org": True, "delete_org": True,
            "view_user": True, "create_user": True, "edit_user": True, "delete_user": True,
            "view_agent": True, "create_agent": True, "edit_agent": True, "delete_agent": True,
            "view_tool": True, "create_tool": True, "edit_tool": True, "delete_tool": True,
            "view_db_connection": True, "create_db_connection": True, "edit_db_connection": True, "delete_db_connection": True,
            "view_chat": True, "create_chat": True, "edit_chat": True, "delete_chat": True,
            "view_chat_session": True, "create_chat_session": True, "edit_chat_session": True, "delete_chat_session": True,
            "view_trace": True, "view_tool_registry": True, "create_super_admin": True, "create_org_admin": True,
            "access_admin_panel": True,
            "view_widget": True, "create_widget": True, "edit_widget": True, "delete_widget": True,
            "view_team": True, "create_team": True, "edit_team": True, "delete_team": True,
            "view_role_permissions": True, "edit_role_permissions": True,
            "view_schedule": True, "create_schedule": True, "edit_schedule": True, "delete_schedule": True,
            "view_project": True, "create_project": True, "edit_project": True, "delete_project": True,
            "view_knowledge_base": True, "create_knowledge_base": True, "edit_knowledge_base": True, "delete_knowledge_base": True,
        },
        "permission_names": [
            "view_org", "create_org", "edit_org", "delete_org",
            "view_user", "create_user", "edit_user", "delete_user",
            "view_agent", "create_agent", "edit_agent", "delete_agent",
            "view_tool", "create_tool", "edit_tool", "delete_tool",
            "view_db_connection", "create_db_connection", "edit_db_connection", "delete_db_connection",
            "view_chat", "create_chat", "edit_chat", "delete_chat",
            "view_chat_session", "create_chat_session", "edit_chat_session", "delete_chat_session",
            "view_trace", "view_tool_registry", "create_super_admin", "create_org_admin",
            "access_admin_panel",
            "view_widget", "create_widget", "edit_widget", "delete_widget",
            "view_team", "create_team", "edit_team", "delete_team",
            "view_role_permissions", "edit_role_permissions",
            "view_schedule", "create_schedule", "edit_schedule", "delete_schedule",
            "view_project", "create_project", "edit_project", "delete_project",
            "view_knowledge_base", "create_knowledge_base", "edit_knowledge_base", "delete_knowledge_base",
        ],
    },
    ROLE_ORG_ADMIN: {
        "label": "Org Admin",
        "description": "Manages a single organization; can create and edit resources.",
        "assign_permission": "create_org_admin",
        "permissions": {
            "view_org": True, "create_org": False, "edit_org": True, "delete_org": True,
            "view_user": True, "create_user": True, "edit_user": True, "delete_user": True,
            "view_agent": True, "create_agent": True, "edit_agent": True, "delete_agent": True,
            "view_tool": True, "create_tool": True, "edit_tool": True, "delete_tool": True,
            "view_db_connection": True, "create_db_connection": True, "edit_db_connection": True, "delete_db_connection": True,
            "view_chat": True, "create_chat": True, "edit_chat": True, "delete_chat": True,
            "view_chat_session": True, "create_chat_session": True, "edit_chat_session": True, "delete_chat_session": True,
            "view_trace": True, "view_tool_registry": True, "access_admin_panel": True,
            "view_widget": True, "create_widget": True, "edit_widget": True, "delete_widget": True,
            "view_team": True, "create_team": True, "edit_team": True, "delete_team": True,
            "view_role_permissions": True, "edit_role_permissions": True,
            "view_schedule": True, "create_schedule": True, "edit_schedule": True, "delete_schedule": True,
            "view_project": True, "create_project": True, "edit_project": True, "delete_project": True,
            "view_knowledge_base": True, "create_knowledge_base": True, "edit_knowledge_base": True, "delete_knowledge_base": True,
        },
        "permission_names": [
            "view_org", "edit_org", "delete_org",
            "view_user", "create_user", "edit_user", "delete_user",
            "view_agent", "create_agent", "edit_agent", "delete_agent",
            "view_tool", "create_tool", "edit_tool", "delete_tool",
            "view_db_connection", "create_db_connection", "edit_db_connection", "delete_db_connection",
            "view_chat", "create_chat", "edit_chat", "delete_chat",
            "view_chat_session", "create_chat_session", "edit_chat_session", "delete_chat_session",
            "view_trace", "view_tool_registry", "access_admin_panel",
            "view_widget", "create_widget", "edit_widget", "delete_widget",
            "view_team", "create_team", "edit_team", "delete_team",
            "view_role_permissions", "edit_role_permissions",
            "view_schedule", "create_schedule", "edit_schedule", "delete_schedule",
            "view_project", "create_project", "edit_project", "delete_project",
            "view_knowledge_base", "create_knowledge_base", "edit_knowledge_base", "delete_knowledge_base",
        ],
    },
    ROLE_ORG_MANAGER: {
        "label": "Org Manager",
        "description": "Can view and edit resources, but not create or delete.",
        "assign_permission": None,
        "permissions": {
            "view_org": True, "create_org": False, "edit_org": True, "delete_org": False,
            "view_user": True, "create_user": False, "edit_user": False, "delete_user": False,
            "view_agent": True, "create_agent": False, "edit_agent": True, "delete_agent": False,
            "view_tool": True, "create_tool": False, "edit_tool": True, "delete_tool": False,
            "view_db_connection": True, "create_db_connection": False, "edit_db_connection": False, "delete_db_connection": False,
            "view_chat": True, "create_chat": True, "edit_chat": True, "delete_chat": False,
            "view_chat_session": True, "create_chat_session": True, "edit_chat_session": True, "delete_chat_session": False,
            "view_trace": True, "view_tool_registry": True,
            "view_widget": True, "create_widget": False, "edit_widget": True, "delete_widget": False,
            "view_team": True, "create_team": False, "edit_team": True, "delete_team": False,
            "view_schedule": True, "create_schedule": True, "edit_schedule": True, "delete_schedule": False,
            "view_project": True, "create_project": False, "edit_project": True, "delete_project": False,
            "view_knowledge_base": True, "create_knowledge_base": True, "edit_knowledge_base": True, "delete_knowledge_base": True,
        },
        "permission_names": [
            "view_org", "edit_org",
            "view_user",
            "view_agent", "edit_agent",
            "view_tool", "edit_tool",
            "view_db_connection",
            "view_chat", "create_chat", "edit_chat",
            "view_chat_session", "create_chat_session", "edit_chat_session",
            "view_trace", "view_tool_registry",
            "view_widget", "edit_widget",
            "view_team", "edit_team",
            "view_schedule", "create_schedule", "edit_schedule",
            "view_project", "edit_project",
            "view_knowledge_base", "create_knowledge_base", "edit_knowledge_base", "delete_knowledge_base",
        ],
    },
    ROLE_USER: {
        "label": "User",
        "description": "Read-only access with basic chat capability.",
        "assign_permission": None,
        "permissions": {
            "view_org": True, "create_org": False, "edit_org": False, "delete_org": False,
            "view_user": True, "create_user": False, "edit_user": False, "delete_user": False,
            "view_agent": True, "create_agent": False, "edit_agent": False, "delete_agent": False,
            "view_tool": True, "create_tool": False, "edit_tool": False, "delete_tool": False,
            "view_db_connection": True, "create_db_connection": False, "edit_db_connection": False, "delete_db_connection": False,
            "view_chat": True, "create_chat": True, "edit_chat": False, "delete_chat": False,
            "view_chat_session": True, "create_chat_session": True, "edit_chat_session": False, "delete_chat_session": False,
            "view_trace": True, "view_tool_registry": True,
            "view_widget": True, "create_widget": False, "edit_widget": False, "delete_widget": False,
            "view_team": True, "create_team": False, "edit_team": False, "delete_team": False,
            "view_schedule": True, "create_schedule": True, "edit_schedule": True, "delete_schedule": False,
            "view_project": True, "create_project": False, "edit_project": False, "delete_project": False,
            "view_knowledge_base": True, "create_knowledge_base": True, "edit_knowledge_base": True, "delete_knowledge_base": True,
        },
        "permission_names": [
            "view_org", "view_user", "view_agent", "view_tool", "view_db_connection",
            "view_chat", "create_chat",
            "view_chat_session", "create_chat_session",
            "view_trace", "view_tool_registry",
            "view_widget",
            "view_team",
            "view_schedule", "create_schedule", "edit_schedule",
            "view_project",
            "view_knowledge_base", "create_knowledge_base", "edit_knowledge_base", "delete_knowledge_base",
        ],
    },
}
